export const storiesData = [
    {
        data: "April 16th 2020",
        name: "The Mountains",
        author: "by John Appleseed",
        mobileImg: "/assets/stories/mobile/mountains.jpg",
        desktopImg: "/assets/stories/desktop/mountains.jpg",
    },
    {
        data: "April 14th 2020",
        name: "Sunset Cityscapes",
        author: "by Benjamin Cruz",
        mobileImg: "/assets/stories/mobile/cityscapes.jpg",
        desktopImg: "/assets/stories/desktop/cityscapes.jpg",
    },
    {
        data: "April 11th 2020",
        name: "18 Days Voyage",
        author: "by Alexei Borodin",
        mobileImg: "/assets/stories/mobile/18-days-voyage.jpg",
        desktopImg: "/assets/stories/desktop/18-days-voyage.jpg",
    },
    {
        data: "April 9th 2020",
        name: "Architecturals",
        author: "by Samantha Brooke",
        mobileImg: "/assets/stories/mobile/architecturals.jpg",
        desktopImg: "/assets/stories/desktop/architecturals.jpg",
    },
    {
        data: "April 7th 2020",
        name: "World Tour 2019",
        author: "by Timothy Wagner",
        mobileImg: "/assets/stories/mobile/world-tour.jpg",
        desktopImg: "/assets/stories/desktop/world-tour.jpg",
    },
    {
        data: "April 3rd 2020",
        name: "Unforeseen Corners",
        author: "by William Malcolm",
        mobileImg: "/assets/stories/mobile/unforeseen-corners.jpg",
        desktopImg: "/assets/stories/desktop/unforeseen-corners.jpg",
    },
    {
        data: "March 29th 2020",
        name: "King on Africa: Part II",
        author: "by Tim Hillenburg",
        mobileImg: "/assets/stories/mobile/king-on-africa.jpg",
        desktopImg: "/assets/stories/desktop/king-on-africa.jpg",
    },
    {
        data: "March 21st 2020",
        name: "The Trip to Nowhere",
        author: "by Felicia Rourke",
        mobileImg: "/assets/stories/mobile/trip-to-nowhere.jpg",
        desktopImg: "/assets/stories/desktop/trip-to-nowhere.jpg",
    },
    {
        data: "March 19th 2020",
        name: "Rage of The Sea",
        author: "by Mohammed Abdul",
        mobileImg: "/assets/stories/mobile/rage-of-the-sea.jpg",
        desktopImg: "/assets/stories/desktop/rage-of-the-sea.jpg",
    },
    {
        data: "March 16th 2020",
        name: "Running Free",
        author: "by Michelle",
        mobileImg: "/assets/stories/mobile/running-free.jpg",
        desktopImg: "/assets/stories/desktop/running-free.jpg",
    },
    {
        data: "March 11th 2020",
        name: "Behind the Waves",
        author: "by Lamarr Wilson",
        mobileImg: "/assets/stories/mobile/behind-the-waves.jpg",
        desktopImg: "/assets/stories/desktop/behind-the-waves.jpg",
    },
    {
        data: "March 9th 2020",
        name: "Calm Waters",
        author: "by Samantha Brooke",
        mobileImg: "/assets/stories/mobile/calm-waters.jpg",
        desktopImg: "/assets/stories/desktop/calm-waters.jpg",
    },
    {
        data: "March 5th 2020",
        name: "The Milky Way",
        author: "by Benjamin Cruz",
        mobileImg: "/assets/stories/mobile/milky-way.jpg",
        desktopImg: "/assets/stories/desktop/milky-way.jpg",
    },
    {
        data: "March 4th 2020",
        name: "Night at The Dark Forest",
        author: "by  Mohammed Abdul",
        mobileImg: "/assets/stories/mobile/dark-forest.jpg",
        desktopImg: "/assets/stories/desktop/dark-forest.jpg",
    },
    {
        data: "March 1st 2020",
        name: "Somwarpet’s Beauty",
        author: "by Michelle",
        mobileImg: "/assets/stories/mobile/somwarpet.jpg",
        desktopImg: "/assets/stories/desktop/somwarpet.jpg",
    },
    {
        data: "February 25th 2020",
        name: "Land of Dreams",
        author: "by William Malcolm",
        mobileImg: "/assets/stories/mobile/land-of-dreams.jpg",
        desktopImg: "/assets/stories/desktop/land-of-dreams.jpg",
    },
];